import React, { useEffect, useMemo, useState } from "react";
import {
  ActivityIndicator,
  Alert,
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useAuth } from "../contexts/AuthContext";

const C = {
  bg: "#F3F7FB",
  surface: "#FFFFFF",
  text: "#102033",
  subtext: "#526277",
  muted: "#7C8A9A",
  border: "#DCE5EF",
  primary: "#0F62FE",
  primaryDark: "#0A3E9B",
  success: "#16A34A",
  successSoft: "#DCFCE7",
  accent: "#E8F0FF",
};

const fmtDate = (value) => {
  if (!value) return "-";
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? "-" : date.toLocaleDateString();
};

export default function PaymentSuccessScreen({ navigation, route }) {
  const insets = useSafeAreaInsets();
  const { refreshBillingPlan } = useAuth();
  const [downloading, setDownloading] = useState(false);
  const planName = route?.params?.planName || "Selected";
  const finalPrice = route?.params?.finalPrice;
  const renewDate = route?.params?.renewDate;
  const receipt = route?.params?.receipt || null;
  const displayCurrency = route?.params?.displayCurrency || "INR";
  const usdInrRate = route?.params?.usdInrRate || 83;
  const symbol = String(displayCurrency).toUpperCase() === "USD" ? "$" : "\u20B9";

  const formattedAmount = useMemo(() => {
    const usd = Number(finalPrice || 0);
    if (String(displayCurrency).toUpperCase() === "USD") {
      return `${symbol}${usd.toFixed(2)}`;
    }
    const rate = Number(usdInrRate || 0);
    const inr = Number.isFinite(rate) && rate > 0 ? usd * rate : usd;
    return `${symbol}${Math.round(inr).toLocaleString("en-IN")}`;
  }, [displayCurrency, finalPrice, symbol, usdInrRate]);

  useEffect(() => {
    refreshBillingPlan?.().catch(() => {});
  }, [refreshBillingPlan]);

  const receiptHtml = useMemo(() => {
    const amountLabel = receipt?.amountInr
      ? `INR ${Number(receipt.amountInr).toFixed(2)}`
      : formattedAmount;
    return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <style>
      body { font-family: Arial, sans-serif; padding: 32px; color: #102033; }
      .sheet { border: 1px solid #dce5ef; border-radius: 20px; padding: 28px; }
      .top { display:flex; justify-content:space-between; align-items:flex-start; margin-bottom: 22px; }
      .brand { font-size: 26px; font-weight: 800; color: #0f62fe; }
      .tag { color:#526277; font-size: 12px; letter-spacing: 1px; text-transform: uppercase; }
      .title { font-size: 22px; font-weight: 800; margin: 18px 0 6px; }
      .sub { color:#526277; margin-bottom: 22px; }
      table { width:100%; border-collapse: collapse; margin-top: 12px; }
      td { padding: 12px 0; border-bottom: 1px solid #e8eef5; vertical-align: top; }
      td:first-child { color:#6b7b8d; width: 38%; }
      td:last-child { text-align:right; font-weight: 700; }
      .foot { margin-top: 26px; color:#6b7b8d; font-size: 12px; }
    </style>
  </head>
  <body>
    <div class="sheet">
      <div class="top">
        <div>
          <div class="brand">NeoApp</div>
          <div class="tag">Payment Receipt</div>
        </div>
        <div style="text-align:right">
          <div style="font-size:14px;font-weight:700">${receipt?.receiptNumber || "-"}</div>
          <div style="color:#6b7b8d;font-size:12px">${receipt?.paidAtLabel || "-"}</div>
        </div>
      </div>
      <div class="title">Subscription Activated</div>
      <div class="sub">Your payment was received successfully and the plan is active now.</div>
      <table>
        <tr><td>Plan</td><td>${planName}</td></tr>
        <tr><td>Amount Paid</td><td>${amountLabel}</td></tr>
        <tr><td>Renew Date</td><td>${fmtDate(renewDate)}</td></tr>
        <tr><td>Payment ID</td><td>${receipt?.paymentId || "-"}</td></tr>
        <tr><td>Order ID</td><td>${receipt?.orderId || "-"}</td></tr>
        <tr><td>Customer</td><td>${receipt?.customerName || "-"}</td></tr>
        <tr><td>Email</td><td>${receipt?.customerEmail || "-"}</td></tr>
      </table>
      <div class="foot">Generated by NeoApp billing flow.</div>
    </div>
  </body>
</html>`;
  }, [formattedAmount, planName, receipt, renewDate]);

  const onDownloadReceipt = async () => {
    if (!receipt) return;
    try {
      setDownloading(true);
      const file = await Print.printToFileAsync({
        html: receiptHtml,
        base64: false,
      });

      const available = await Sharing.isAvailableAsync();
      if (available) {
        await Sharing.shareAsync(file.uri, {
          mimeType: "application/pdf",
          dialogTitle: "Download receipt PDF",
          UTI: "com.adobe.pdf",
        });
      } else {
        Alert.alert("Receipt Ready", `PDF saved at:\n${file.uri}`);
      }
    } catch (e) {
      Alert.alert("Receipt Failed", e?.message || "Unable to generate receipt PDF");
    } finally {
      setDownloading(false);
    }
  };

  const onContinue = async () => {
    await refreshBillingPlan?.().catch(() => {});
    navigation.reset({
      index: 0,
      routes: [{ name: "Main" }],
    });
  };

  const detailRows = [
    { label: "Amount Paid", value: formattedAmount },
    { label: "Renew Date", value: fmtDate(renewDate) },
    { label: "Receipt No", value: receipt?.receiptNumber || "-" },
    { label: "Payment ID", value: receipt?.paymentId || "-" },
    { label: "Order ID", value: receipt?.orderId || "-" },
    { label: "Receipt Email", value: receipt?.customerEmail || "-" },
  ];

  return (
    <SafeAreaView style={[styles.container, { paddingTop: insets.top }]}>
      <StatusBar barStyle="dark-content" backgroundColor={C.bg} />
      <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
        <LinearGradient
          colors={["#F8FFFB", "#EEF4FF"]}
          start={{ x: 0, y: 0 }}
          end={{ x: 1, y: 1 }}
          style={styles.hero}
        >
          <View style={styles.badgeRing}>
            <View style={styles.badgeCore}>
              <Ionicons name="checkmark" size={34} color={C.success} />
            </View>
          </View>
          <Text style={styles.title}>Payment Successful</Text>
          <Text style={styles.subtitle}>Your {planName} plan is active and ready to use.</Text>
        </LinearGradient>

        <View style={styles.receiptCard}>
          <View style={styles.receiptHeader}>
            <View>
              <Text style={styles.receiptEyebrow}>Receipt</Text>
              <Text style={styles.receiptNumber}>{receipt?.receiptNumber || "Preparing receipt"}</Text>
            </View>
            <View style={styles.receiptStamp}>
              <Ionicons name="shield-checkmark" size={18} color={C.primary} />
              <Text style={styles.receiptStampText}>Verified</Text>
            </View>
          </View>

          <View style={styles.planChip}>
            <Ionicons name="diamond-outline" size={16} color={C.primary} />
            <Text style={styles.planChipText}>{planName}</Text>
          </View>

          <View style={styles.detailList}>
            {detailRows.map((item) => (
              <View key={item.label} style={styles.detailRow}>
                <Text style={styles.detailLabel}>{item.label}</Text>
                <Text style={styles.detailValue} numberOfLines={2}>
                  {item.value}
                </Text>
              </View>
            ))}
          </View>
        </View>

        <TouchableOpacity
          style={[styles.secondaryBtn, downloading && styles.disabledBtn]}
          onPress={onDownloadReceipt}
          disabled={!receipt || downloading}
          activeOpacity={0.9}
        >
          {downloading ? <ActivityIndicator color={C.text} /> : <Ionicons name="download-outline" size={18} color={C.text} />}
          <Text style={styles.secondaryBtnText}>
            {downloading ? "Generating PDF..." : "Download Receipt PDF"}
          </Text>
        </TouchableOpacity>

        <TouchableOpacity style={styles.primaryBtn} onPress={onContinue} activeOpacity={0.92}>
          <Text style={styles.primaryBtnText}>Continue To Home</Text>
          <Ionicons name="arrow-forward" size={18} color="#fff" />
        </TouchableOpacity>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: C.bg,
  },
  content: {
    padding: 20,
    paddingBottom: 32,
    gap: 16,
  },
  hero: {
    borderRadius: 28,
    paddingHorizontal: 22,
    paddingVertical: 28,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#D9E7FF",
  },
  badgeRing: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: "rgba(22,163,74,0.10)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  badgeCore: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: C.successSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    fontSize: 28,
    fontWeight: "900",
    color: C.text,
  },
  subtitle: {
    marginTop: 8,
    fontSize: 15,
    lineHeight: 22,
    textAlign: "center",
    color: C.subtext,
  },
  receiptCard: {
    backgroundColor: C.surface,
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: C.border,
    shadowColor: "#163A63",
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  receiptHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  receiptEyebrow: {
    fontSize: 12,
    fontWeight: "800",
    color: C.muted,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  receiptNumber: {
    marginTop: 4,
    fontSize: 20,
    fontWeight: "900",
    color: C.text,
  },
  receiptStamp: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: C.accent,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
  },
  receiptStampText: {
    fontSize: 12,
    fontWeight: "800",
    color: C.primaryDark,
  },
  planChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#F4F8FF",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 16,
  },
  planChipText: {
    fontSize: 15,
    fontWeight: "800",
    color: C.primaryDark,
  },
  detailList: {
    gap: 10,
  },
  detailRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#EDF2F7",
    gap: 16,
  },
  detailLabel: {
    flex: 1,
    fontSize: 13,
    fontWeight: "700",
    color: C.muted,
  },
  detailValue: {
    flex: 1.2,
    fontSize: 14,
    fontWeight: "800",
    color: C.text,
    textAlign: "right",
  },
  secondaryBtn: {
    minHeight: 54,
    borderRadius: 18,
    backgroundColor: "#EAF0F6",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 10,
  },
  secondaryBtnText: {
    fontSize: 15,
    fontWeight: "900",
    color: C.text,
  },
  primaryBtn: {
    minHeight: 56,
    borderRadius: 18,
    backgroundColor: C.primary,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 10,
  },
  primaryBtnText: {
    fontSize: 16,
    fontWeight: "900",
    color: "#fff",
  },
  disabledBtn: {
    opacity: 0.7,
  },
});
