const mongoose = require("mongoose");

const ENQUIRY_STATUSES = [
  "New",
  "Contacted",
  "Interested",
  "Not Interested",
  "Converted",
  "Closed",
  // Backward compatibility for older mobile/web clients and existing data
  "In Progress",
  "Dropped",
];

const enquirySchema = new mongoose.Schema(
  {
    enqNo: { type: String, unique: true }, // Auto-generated by server
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    assignedTo: { type: mongoose.Schema.Types.ObjectId, ref: "User" }, // Assigned staff member
    date: { type: String, required: true }, // YYYY-MM-DD format
    enquiryDateTime: { type: Date, default: Date.now },
    enqBy: { type: String },

    // Customer Details
    enqType: String,
    source: String,
    name: { type: String, required: true },
    mobile: { type: String, required: true },
    email: String,
    altMobile: String,
    address: String,
    image: String, // Store image path or base64 string

    // Product Details
    product: { type: String, required: true },
    variant: String,
    color: String,
    cost: { type: Number, required: true }, // This maps to "Lead Value"
    paymentMethod: String,
    conversionDate: Date, // Track when it became a sale
    refundDate: Date, // Track if sale was revoked

    lastContactedAt: Date,
    callCount: { type: Number, default: 0 },

    status: {
      type: String,
      enum: ENQUIRY_STATUSES,
      default: "New",
    },

    createdAt: { type: Date, default: Date.now },
  },
  { timestamps: true },
);

// Indexes for performance
enquirySchema.index({ userId: 1, status: 1 });
enquirySchema.index({ userId: 1, date: -1 });
enquirySchema.index({ assignedTo: 1, status: 1 });
enquirySchema.index({ assignedTo: 1, date: -1 });
enquirySchema.index({ userId: 1, assignedTo: 1, createdAt: -1 });
enquirySchema.index({ name: "text", mobile: "text", email: "text" });
enquirySchema.index({ mobile: 1 });

module.exports = mongoose.model("Enquiry", enquirySchema);
module.exports.ENQUIRY_STATUSES = ENQUIRY_STATUSES;
